# Generated by Django 2.1.1 on 2020-02-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_group',
            field=models.IntegerField(choices=[(0, 'student'), (1, 'teacher'), (2, 'admin')], default=0),
        ),
    ]
