# Generated by Django 2.1.1 on 2020-02-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_auth', '0004_remove_profile_access_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.IntegerField(choices=[(-1, 'demo'), (0, 'student'), (1, 'teacher'), (2, 'admin')], default=0),
        ),
    ]
