# Generated by Django 2.1.1 on 2018-09-29 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0002_auto_20180911_0820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relation',
            new_name='UserCourseRelation',
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(null=True, upload_to='answers/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='questions/', verbose_name='Изображение'),
        ),
    ]
