# Generated by Django 2.1.1 on 2018-10-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_sessionanswer_current_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionanswer',
            name='will_send_hint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
