# Generated by Django 2.1.1 on 2018-10-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20181004_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesession',
            old_name='attempt_number',
            new_name='attempts_number',
        ),
        migrations.RenameField(
            model_name='sessionquestion',
            old_name='attempt_number',
            new_name='attempts_number',
        ),
        migrations.RenameField(
            model_name='sessionquestion',
            old_name='orderNumber',
            new_name='order_number',
        ),
        migrations.AddField(
            model_name='course',
            name='good_mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='perfect_mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='satisfactory_mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='attempts_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='timer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sessionanswer',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
