# Generated by Django 2.1.1 on 2018-10-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_course_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourserelation',
            old_name='user',
            new_name='user_of_course',
        ),
    ]
