# Generated by Django 2.1.1 on 2018-10-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20181005_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourserelation',
            old_name='user_of_course',
            new_name='user',
        ),
    ]
