# Generated by Django 2.1.1 on 2018-10-05 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20181005_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(related_name='user', through='exam.UserCourseRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
