# Generated by Django 2.1.1 on 2020-02-05 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='answers/', verbose_name='Изображение')),
                ('audio', models.FileField(null=True, upload_to='answers_audio/')),
                ('hint_old', models.CharField(max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение')),
                ('questions_number', models.IntegerField()),
                ('attempts', models.IntegerField(null=True)),
                ('perfect_mark', models.IntegerField(null=True)),
                ('perfect_audio', models.FileField(null=True, upload_to='courses_audio/')),
                ('good_mark', models.IntegerField(null=True)),
                ('good_audio', models.FileField(null=True, upload_to='courses_audio/')),
                ('satisfactory_mark', models.IntegerField(null=True)),
                ('satisfactory_audio', models.FileField(null=True, upload_to='courses_audio/')),
                ('bad_audio', models.FileField(null=True, upload_to='courses_audio/')),
                ('video', models.CharField(max_length=255, null=True)),
                ('version', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(null=True, upload_to='hint_audio/')),
                ('video', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(blank=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_manage.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('answer_type', models.IntegerField(verbose_name='Тип вопроса')),
                ('image', models.ImageField(null=True, upload_to='questions/', verbose_name='Изображение')),
                ('difficulty', models.IntegerField(verbose_name='Сложность')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('answers_number', models.IntegerField(null=True)),
                ('audio', models.FileField(null=True, upload_to='questions_audio/')),
                ('attempts_number', models.IntegerField(null=True)),
                ('timer', models.IntegerField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=255, null=True)),
                ('audio', models.FileField(null=True, upload_to='questions_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsSubscriptionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribtion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrictMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='strict_modes/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.IntegerField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_manage.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionmedia',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_manage.StrictMode'),
        ),
        migrations.AddField(
            model_name='questionmedia',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_manage.Question'),
        ),
        migrations.AddField(
            model_name='hint',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_manage.StrictMode'),
        ),
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(blank=True, to='exam_manage.Question'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(related_name='user', through='exam_manage.UserCourseRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_manage.Question'),
        ),
    ]
