# Generated by Django 2.1.1 on 2020-02-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_manage', '0002_questionssubscriptionrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='strictmode',
            name='image_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='strictmode',
            name='image',
            field=models.ImageField(null=True, upload_to='strict_modes/'),
        ),
    ]
