# Generated by Django 2.1.1 on 2020-02-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_manage', '0003_auto_20200208_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.CharField(max_length=1024, null=True, verbose_name='Изображение'),
        ),
    ]
