# Generated by Django 2.1.1 on 2020-02-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_manage', '0004_auto_20200227_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strictmode',
            name='image',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
