# Generated by Django 2.1.1 on 2020-02-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_manage', '0005_auto_20200227_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='questions/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='strictmode',
            name='image',
            field=models.ImageField(null=True, upload_to='strict_modes/'),
        ),
    ]
