# Generated by Django 2.1.1 on 2020-02-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_manage', '0006_auto_20200227_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
