# Generated by Django 2.1.1 on 2020-02-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_manage', '0008_auto_20200227_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='demo_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
